# Generated by Django 5.0.3 on 2025-05-25 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Izlozhba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('date_pochetok', models.DateTimeField()),
                ('date_kraj', models.DateTimeField()),
                ('opis', models.TextField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Umetnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('umetnichki_stil', models.CharField(choices=[('im', 'Impressionism'), ('pa', 'Pop art'), ('gr', 'Graffiti')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UmetnichkoDelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('izlozhba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.izlozhba')),
                ('umetnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.umetnik')),
            ],
        ),
    ]
